stages:
    - build
    - upload

#
# Build
#

build:
    stage: build
    script:
        - wowui-builder build --vcs-tag=$CI_BUILD_TAG --dist-dir=dist/

    artifacts:
        paths:
            - dist/

#
# Upload
#

upload-wowi:
    only:
        - tags
    stage: upload
    dependencies:
        - build
    script:
        - wowui-builder upload --dist-dir=dist/ wowi

upload-curse:
    only:
        - tags
    stage: upload
    dependencies:
        - build
    script:
        - wowui-builder upload --dist-dir=dist/ curse

