name: Package and Release

on:
  push:
    tags: '*.*.*-*'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_OAUTH: ${{ secrets.TOKEN_FOR_UPLOAD }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Packager
        uses: BigWigsMods/packager@master
